### ISSUE TITLE
Enabling multilib on pacman.conf doesn't enable?

### ISSUE THREAD

**Issue by birdup000** [blend-os/blendOS#129]
Hi I'm trying to install Steam which is in the multilib repository from the Arch Repo I uncommented those 2 lines in the multilib repository, uncomment the [multilib] section in /etc/pacman.conf for it and tried running ``` sudo akshara update ``` and it says ```error: target not found: steam``` with ```[ERROR] failed to download packages``` am I doing something incorrectly? (I am very new to this distro and trying to wrap my head about why it isn't working)

my current system.yaml looks like this

```yaml
impl: http://github.com/blend-os/tracks/raw/main
packages:
- nvidia-dkms
- nvidia-prime
- switcheroo-control
- firefox
- flatpak
- docker
- docker-compose
- steam
aur-packages:
    - 'rtl8852bu-dkms-git'
    - 'visual-studio-code-bin'
    - 'github-desktop-bin'
    - 'nvidia-settings'
    - 'minecraft-launcher'
repo: https://pkg-repo.blendos.co
services:
- switcheroo-control
track: cinnamon
```
